repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: '^tests/data/daily_bio_bert_indexed/.*\.json$'
      - id: end-of-file-fixer
        exclude: '^tests/data/daily_bio_bert_indexed/.*\.json$'
      - id: trailing-whitespace
        exclude: '^tests/data/daily_bio_bert_indexed/.*\.json$'

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.4.9"
    hooks:
      - id: ruff
        name: ruff
        exclude: '^tests/data/daily_bio_bert_indexed/.*\.json$'
      - id: ruff-format
        name: ruff-format
        exclude: '^tests/data/daily_bio_bert_indexed/.*\.json$'

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        name: mypy
        additional_dependencies: ["types-requests"]

  - repo: https://github.com/pycqa/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        name: docformatter
        args:
          [
            -r,
            -i,
            --pre-summary-newline,
            --make-summary-multi-line,
            --wrap-summaries,
            "120",
            --wrap-descriptions,
            "120",
            medirag,
            tests,
          ]

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        name: bandit
        exclude: ^tests/
        args:
          - -r
          - medirag

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        exclude: '^(poetry.lock|tests/data/daily_bio_bert_indexed/.*\.json)$'
