[tool.poetry]
name = "medirag"
version = "0.1.0"
description = ""
authors = ["Alvin Henrick <alvin@equilibriumenergy.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
llama-index = "^0.10.65"
llama-index-vector-stores-faiss = "^0.1.2"
llama-index-embeddings-huggingface = "^0.2.3"
beautifulsoup4 = "^4.12.3"
lxml = "^5.3.0"
langchain = "^0.2.13"
faiss-cpu = "^1.8.0.post1"
sentence-transformers = "^3.0.1"
tqdm = "^4.66.5"
transformers = "^4.44.0"
torch = "^2.4.0"
nltk = "3.8.1"
dspy-ai = "^2.4.13"
python-dotenv = "^1.0.1"
accelerate = "^0.33.0"
gradio = "^4.41.0"
pydantic = "^2.8.2"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
pre-commit = "^3.8.0"
pytest-cov = "^5.0.0"
types-requests = "^2.32.0.20240712"
mypy = "^1.11.1"
pytest-mock = "^3.14.0"


[tool.ruff]
extend-exclude = [
    "__pycache__",
    "build",
    "dist",
]
# Same as Black.
line-length = 120

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "-vvv -s"
testpaths = "tests"
