name: Sync to Hugging Face hub

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository with LFS
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Fetch all LFS objects
        run: git lfs fetch --all

      - name: Pull latest changes from Hugging Face Hub
        run: |
          git pull --rebase https://${{ vars.HF_USERNAME }}:$HF_TOKEN@huggingface.co/spaces/${{ vars.HF_USERNAME }}/medirag main

      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://${{ vars.HF_USERNAME }}:$HF_TOKEN@huggingface.co/spaces/${{ vars.HF_USERNAME }}/medirag main
